# 2. SQL Analysis

## 2.1. Data Loading

Install and import all required R libraries

In [1]:
install.packages(c("sqldf", "googledrive"), quiet = TRUE)

library(sqldf)
library(googledrive)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite

Mount Google Drive to read the cleaned dataset

In [2]:
drive_auth(use_oob=TRUE)

Is it OK to cache OAuth access credentials in the folder ~/.cache/gargle
between R sessions?
1: Yes
2: No
Enter a number between 1 and 2, or enter 0 to exit.
Please point your browser to the following url:

https://accounts.google.com/o/oauth2/v2/auth?client_id=603366585132-frjlouoa3s2ono25d2l9ukvhlsrlnr7k.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=https%3A%2F%2Fwww.tidyverse.org%2Fgoogle-callback%2F&response_type=code&state=c64c23126141b3f11d250fc63ab3a9f2&access_type=offline&prompt=consent

In [4]:
base <- "North Star Case Study Dataset/cleaned/"

dl <- function(name) {
  drive_download(paste0(base, name), overwrite = TRUE)$local_path
}

# NOTE: stringsAsFactors tells R to keep text columns as strings, rather than converting them into categories
hubs <- read.csv(dl("hubs_clean.csv"), stringsAsFactors=FALSE)
customers <- read.csv(dl("customers_clean.csv"), stringsAsFactors=FALSE)
drivers <- read.csv(dl("drivers_clean.csv"), stringsAsFactors=FALSE)
vehicles <- read.csv(dl("vehicles_clean.csv"), stringsAsFactors=FALSE)
orders <- read.csv(dl("orders_clean.csv"), stringsAsFactors=FALSE)
deliveries <- read.csv(dl("deliveries_clean.csv"), stringsAsFactors=FALSE)
incidents <- read.csv(dl("incidents_clean.csv"), stringsAsFactors=FALSE)
complaints <- read.csv(dl("complaints_clean.csv"), stringsAsFactors=FALSE)
app_events <- read.csv(dl("app_events_clean.csv"), stringsAsFactors=FALSE)

File downloaded:

• hubs_clean.csv <id: 1DYLnMQnsQDEGyg1nl93Nxk0FoFBX-5Rk>

Saved locally as:

• hubs_clean.csv

File downloaded:

• customers_clean.csv <id: 1wvGKg18PTzOXvS3zgF7edFBumiPrKeo3>

Saved locally as:

• customers_clean.csv

File downloaded:

• drivers_clean.csv <id: 1ZGAHu6PfaoA1KVod2Cb318kH86o617z2>

Saved locally as:

• drivers_clean.csv

File downloaded:

• vehicles_clean.csv <id: 1JMEYq8khDKpkNLK9BoYFy42DSa8sL1qy>

Saved locally as:

• vehicles_clean.csv

File downloaded:

• orders_clean.csv <id: 13WWlNXhsfPXwHMTqwLxA16lrdcufljuB>

Saved locally as:

• orders_clean.csv

File downloaded:

• deliveries_clean.csv <id: 1i4v-y1YnzmtW9NJ-keXHiStL8eMKdqIV>

Saved locally as:

• deliveries_clean.csv

File downloaded:

• incidents_clean.csv <id: 1sqHskG5ZMhfTodFiSwuj53zU-Az892Ds>

Saved locally as:

• incidents_clean.csv

File downloaded:

• complaints_clean.csv <id: 11RcmLsZhFaydACSzhLnzPA2ZUHmL8ogD>

Saved locally as:

• complaints_clean.csv

File downloaded:

• app_events_clean.csv <id: 1cGM6efhDF-ismuREjEIBWCE82kUgzdPi>

Saved locally as:

• app_events_clean.csv

## 2.2. Delivery Status Breakdown

Count the number of each delivery status

In [5]:
sqldf("
  SELECT delivery_status,
         COUNT(*) AS total
  FROM deliveries
  GROUP BY delivery_status
  ORDER BY total DESC
")

  delivery_status total
1 OnTime          616
2 Delayed         202
3 Failed          132

## 2.3. Complaint Volume by Type

Which complaint categories are raised most often

In [6]:
sqldf("
  SELECT complaint_type,
         COUNT(*) AS total
  FROM complaints
  GROUP BY complaint_type
  ORDER BY total DESC
")

  complaint_type    total
1 Delay             101
2 MissedPickup       64
3 AppIssue           53
4 DriverBehaviour    51
5 SupportExperience  20
6 Billing            16
7 Damage             15

## 2.4. Hub Performance Summary

Per hub, determine delivery volume, failure count, failure rate and average customer rating

In [7]:
sqldf("
  SELECT h.hub_name,
         COUNT(*) AS total_deliveries,
         SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed,
         ROUND(SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) * 100 / COUNT(*), 1) AS failed_pct,
         ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_rating
  FROM deliveries d
  JOIN hubs h ON d.hub_id = h.hub_id
  GROUP BY h.hub_name
  ORDER BY failed_pct DESC
")

  hub_name       total_deliveries failed failed_pct avg_rating
1 Midtown Relay  128              26     20         3.88
2 Central Core   115              23     20         3.67
3 Airport Hub    104              15     14         3.88
4 West Gate      127              16     12         3.92
5 Riverside Hub  115              14     12         3.88
6 North Exchange 136              17     12         3.84
7 South Link     106              10      9         3.95
8 East Dock      119              11      9         3.90

## 2.5. Failed Delivery Rate by Zone

Which pickup zones have the worst faliure rate

In [8]:
sqldf("
  SELECT o.pickup_zone,
         COUNT(*) AS total,
         SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed,
         ROUND(SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) * 100 / COUNT(*), 1) AS failed_pct
  FROM deliveries d
  JOIN orders o ON d.order_id = o.order_id
  GROUP BY o.pickup_zone
  ORDER BY failed_pct DESC
")

  pickup_zone total failed failed_pct
1 Central     174   33     18
2 North       135   22     16
3 Riverside   119   18     15
4 West        114   14     12
5 East        156   19     12
6 South       139   14     10
7 Airport     113   12     10

## 2.6. Service Type Complaint Rate

Determine complaint rate for each service type, to find out which service type generates the most dissatisfaction

In [9]:
sqldf("
  SELECT o.service_type,
         COUNT(DISTINCT o.order_id) AS orders,
         COUNT(DISTINCT cp.complaint_id) AS complaints,
         ROUND(COUNT(DISTINCT cp.complaint_id) * 100.0 / COUNT(DISTINCT o.order_id), 1) AS complaint_rate_pct
  FROM orders o
  LEFT JOIN complaints cp ON o.order_id = cp.order_id
  GROUP BY o.service_type
  ORDER BY complaint_rate_pct DESC
")

  service_type orders complaints complaint_rate_pct
1 Retail       297    83         27.9
2 Medical      139    37         26.6
3 Parcel       308    77         25.0
4 Passenger    341    84         24.6
5 Business     165    39         23.6

## 2.7. Drive Training vs. Route Overrides

Determine whether it is undertrained drivers that override routes more often

In [10]:
sqldf("
  SELECT CASE
           WHEN dr.training_score < 60  THEN 'Low (<60)'
           WHEN dr.training_score <= 75 THEN 'Mid (60-75)'
           ELSE 'High (>75)'
         END AS training_band,
         COUNT(DISTINCT dr.driver_id) AS drivers,
         ROUND(AVG(d.manual_route_override_count), 2) AS avg_overrides
  FROM deliveries d
  JOIN drivers dr ON d.driver_id = dr.driver_id
  GROUP BY training_band
  ORDER BY avg_overrides DESC
")

  training_band drivers avg_overrides
1 Mid (60-75)   65      1.00
2 High (>75)    89      0.96
3 Low (<60)     16      0.90

## 2.8. Incidents by Vehicle Type

Determine incidents per 100 deliveries in each vehicle type

In [11]:
sqldf("
  SELECT v.vehicle_type,
         COUNT(DISTINCT i.incident_id) AS incidents,
         COUNT(DISTINCT d.delivery_id) AS deliveries,
         ROUND(COUNT(DISTINCT i.incident_id) * 100.0 / COUNT(DISTINCT d.delivery_id), 1) AS incidents_per_100
  FROM deliveries d
  JOIN vehicles v  ON d.vehicle_id = v.vehicle_id
  LEFT JOIN incidents i ON d.delivery_id = i.delivery_id
  GROUP BY v.vehicle_type
  ORDER BY incidents_per_100 DESC
")

  vehicle_type incidents deliveries incidents_per_100
1 Diesel        47       144        32.6
2 CargoVan      67       223        30.0
3 EV           100       339        29.5
4 Hybrid        66       244        27.0

## 2.9. Monthly Operational Trend

Determine order volume, failed deliveries and complaints per month

In [12]:
sqldf("
  SELECT strftime('%Y-%m', o.order_created_at) AS month,
         COUNT(DISTINCT o.order_id) AS orders,
         SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,
         COUNT(DISTINCT cp.complaint_id) AS complaints
  FROM orders o
  LEFT JOIN deliveries d  ON o.order_id = d.order_id
  LEFT JOIN complaints cp ON o.order_id = cp.order_id
  GROUP BY month
  ORDER BY month
")

   month   orders failed_deliveries complaints
1  2024-01 56     1                 17
2  2024-02 59     7                 16
3  2024-03 65     5                 17
4  2024-04 46     6                 15
5  2024-05 45     2                  8
6  2024-06 60     8                 18
7  2024-07 45     6                 12
8  2024-08 56     4                 16
9  2024-09 60     6                 16
10 2024-10 44     6                 10
11 2024-11 66     8                 22
12 2024-12 58     7                 20
13 2025-01 65     8                 13
14 2025-02 49     8                  6
15 2025-03 37     3                 11
16 2025-04 60     5                 16
17 2025-05 45     8                 16
18 2025-06 45     3                 15
19 2025-07 42     7                  8
20 2025-08 45     3                  6
21 2025-09 38     4                 12
22 2025-10 60     7                 12
23 2025-11 50     7                  4
24 2025-12 54     5                 14

## 2.10. Deliveries with both Incidents and Complaints

Determine deliveries that are logged as resolved in one system, and an exception in another

In [13]:
sqldf("
  SELECT d.delivery_id,
         d.order_id,
         d.delivery_status,
         i.incident_type,
         i.severity AS incident_severity,
         cp.complaint_type,
         cp.severity AS complaint_severity
  FROM deliveries d
  JOIN incidents i ON d.delivery_id = i.delivery_id
  JOIN complaints cp ON d.order_id = cp.order_id
  ORDER BY d.delivery_id
")

   delivery_id order_id delivery_status incident_type    incident_severity
1  DL00011     O00202   OnTime          ProofMissing     Medium
2  DL00036     O00652   OnTime          AppSyncError     Low
3  DL00073     O00421   OnTime          TemperatureIssue Critical
4  DL00148     O00817   OnTime          ProofMissing     Medium
5  DL00189     O01227   Failed          CustomerNoShow   High
6  DL00221     O00594   OnTime          BatteryAlert     Medium
7  DL00225     O00056   OnTime          ProofMissing     Medium
8  DL00288     O00636   Delayed         CustomerNoShow   Medium
9  DL00291     O00485   OnTime          ProofMissing     Low
10 DL00294     O00443   OnTime          RouteDeviation   Low
11 DL00294     O00443   OnTime          RouteDeviation   Low
12 DL00306     O01168   Delayed         CustomerNoShow   High
13 DL00317     O00711   OnTime          ProofMissing     Low
14 DL00324     O00455   Failed          ProofMissing     Low
15 DL00324     O00455   Failed          TemperatureIssue Critical
16 DL00366     O00910   OnTime          CustomerNoShow   Medium
17 DL00366     O00910   OnTime          RouteDeviation   Medium
18 DL00373     O00282   Delayed         RouteDeviation   Low
19 DL00376     O01104   OnTime          CustomerNoShow   Medium
20 DL00376     O01104   OnTime          CustomerNoShow   Medium
21 DL00388     O00886   OnTime          ProofMissing     Low
22 DL00463     O00271   OnTime          BatteryAlert     Medium
23 DL00464     O01124   OnTime          TemperatureIssue Medium
24 DL00469     O00458   Delayed         VehicleFault     High
25 DL00475     O01121   OnTime          SafetyNearMiss   Medium
26 DL00508     O00161   OnTime          RouteDeviation   High
27 DL00525     O00351   OnTime          BatteryAlert     Low
28 DL00525     O00351   OnTime          BatteryAlert     Low
29 DL00576     O00483   Failed          ProofMissing     High
30 DL00576     O00483   Failed          ProofMissing     High
⋮  ⋮           ⋮        ⋮               ⋮                ⋮
33 DL00578     O00115   OnTime          VehicleFault     Low
34 DL00590     O00229   Delayed         ProofMissing     Critical
35 DL00633     O00272   OnTime          RouteDeviation   High
36 DL00636     O00880   OnTime          CustomerNoShow   Medium
37 DL00655     O01222   OnTime          ProofMissing     Low
38 DL00688     O00385   OnTime          BatteryAlert     Medium
39 DL00688     O00385   OnTime          RouteDeviation   Medium
40 DL00690     O00129   Failed          VehicleFault     Medium
41 DL00720     O01179   Delayed         TemperatureIssue High
42 DL00739     O00644   Delayed         AppSyncError     Medium
43 DL00743     O00171   OnTime          RouteDeviation   Low
44 DL00748     O00741   Delayed         CustomerNoShow   Low
45 DL00778     O00965   Failed          SafetyNearMiss   High
46 DL00788     O00927   Failed          VehicleFault     Low
47 DL00790     O00628   Delayed         RouteDeviation   High
48 DL00790     O00628   Delayed         RouteDeviation   High
49 DL00806     O00128   Delayed         BatteryAlert     Low
50 DL00810     O00116   OnTime          TemperatureIssue Critical
51 DL00810     O00116   OnTime          TemperatureIssue Medium
52 DL00859     O00512   Delayed         AppSyncError     Medium
53 DL00874     O01012   Delayed         AppSyncError     High
54 DL00882     O01151   OnTime          AppSyncError     Low
55 DL00882     O01151   OnTime          AppSyncError     Low
56 DL00882     O01151   OnTime          BatteryAlert     Medium
57 DL00882     O01151   OnTime          BatteryAlert     Medium
58 DL00907     O00884   OnTime          BatteryAlert     Low
59 DL00915     O00873   OnTime          RouteDeviation   High
60 DL00939     O00417   OnTime          CustomerNoShow   Medium
61 DL00939     O00417   OnTime          CustomerNoShow   Medium
62 DL00944     O00336   OnTime          CustomerNoShow   Medium
   complaint_type    complaint_severity
1  DriverBehaviour   Medium
2  Delay             Medium
3  DriverBehaviour   Medium
4  Delay             Medium
5  DriverBehaviour   Medium
6  DriverBehaviour   High
7  SupportExperience Medium
8  Billing           Medium
9  Delay             Medium
10 AppIssue          Low
11 SupportExperience Low
12 MissedPickup      Low
13 Delay             Low
14 Delay             Medium
15 Delay             Medium
16 DriverBehaviour   Medium
17 DriverBehaviour   Medium
18 Delay             Medium
19 Delay             High
20 MissedPickup      Medium
21 Billing           Medium
22 DriverBehaviour   Low
23 AppIssue          High
24 Damage            High
25 Delay             High
26 MissedPickup      Medium
27 Delay             Low
28 SupportExperience Medium
29 Delay             Medium
30 MissedPickup      Medium
⋮  ⋮                 ⋮
33 SupportExperience Low
34 MissedPickup      Medium
35 DriverBehaviour   Medium
36 AppIssue          Medium
37 DriverBehaviour   High
38 AppIssue          High
39 AppIssue          High
40 MissedPickup      Medium
41 MissedPickup      Medium
42 Delay             Medium
43 MissedPickup      Low
44 AppIssue          Medium
45 SupportExperience Medium
46 SupportExperience High
47 Delay             Medium
48 MissedPickup      Medium
49 Delay             Medium
50 Billing           Low
51 Billing           Low
52 DriverBehaviour   High
53 MissedPickup      Medium
54 MissedPickup      Medium
55 MissedPickup      Medium
56 MissedPickup      Medium
57 MissedPickup      Medium
58 MissedPickup      Medium
59 DriverBehaviour   High
60 Delay             Low
61 DriverBehaviour   Medium
62 DriverBehaviour   Low

## 2.11. Zone-Level Operational Risk

Output total, failed, delayed, missing and complained orders by pickup zone for high-level overview

In [14]:
sqldf("
  SELECT o.pickup_zone,
         COUNT(DISTINCT o.order_id) AS total_orders,
         SUM(CASE WHEN d.delivery_status = 'Failed'  THEN 1 ELSE 0 END) AS failed,
         SUM(CASE WHEN d.delivery_status = 'Delayed' THEN 1 ELSE 0 END) AS delayed,
         SUM(COALESCE(d.proof_of_completion_missing, 0)) AS proof_missing,
         COUNT(DISTINCT cp.complaint_id) AS complaints,
         ROUND(AVG(COALESCE(cp.compensation_amount, 0)), 2) AS avg_compensation
  FROM orders o
  LEFT JOIN deliveries d ON o.order_id = d.order_id
  LEFT JOIN complaints cp ON o.order_id = cp.order_id
  GROUP BY o.pickup_zone
  ORDER BY (failed + delayed + proof_missing) DESC
")

  pickup_zone total_orders failed delayed proof_missing complaints
1 Central     238          33     51      17            60
2 East        207          20     31      11            50
3 North       174          22     22      12            53
4 Riverside   151          19     26       8            45
5 Airport     144          12     31       5            32
6 West        155          14     22      11            34
7 South       181          14     22       7            46
  avg_compensation
1 5.19
2 4.80
3 6.34
4 5.26
5 3.01
6 4.48
7 4.11